home:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

search:
    path:     /search
    defaults: { _controller: AppBundle:Search:search }

find_reservation:
    path:     /status
    defaults: { _controller: AppBundle:Default:index}

show_reservation:
    path:     /status/{id}
    defaults: { _controller: AppBundle:Default:index}

test:
    path:     /test
    defaults: { _controller: AppBundle:Default:test}

booking:
    path:     /booking
    defaults: { _controller: AppBundle:Default:book}

confirmation:
    path:     /confirmation
    defaults: { _controller: AppBundle:Booking:index}
